const scienceSets = {
            easy: {
                biology: [
                    { question: "What part of the plant makes food?", correct: "Leaf", wrong: ["Root", "Stem", "Flower"] },
                    { question: "What do humans need to breathe?", correct: "Oxygen", wrong: ["Carbon dioxide", "Nitrogen", "Hydrogen"] },
                    { question: "What is the basic unit of life?", correct: "Cell", wrong: ["Tissue", "Organ", "Organism"] },
                    { question: "What do bees collect from flowers?", correct: "Nectar", wrong: ["Leaves", "Seeds", "Roots"] },
                    { question: "Which organ pumps blood in humans?", correct: "Heart", wrong: ["Lungs", "Brain", "Liver"] },
                    { question: "Which part of the body helps us smell?", correct: "Nose", wrong: ["Eyes", "Ears", "Mouth"] },
                    { question: "Which organ helps us breathe?", correct: "Lungs", wrong: ["Heart", "Stomach", "Kidneys"] },
                    { question: "What do fish use to breathe?", correct: "Gills", wrong: ["Lungs", "Skin", "Fins"] },
                    { question: "What do cows give us to drink?", correct: "Milk", wrong: ["Water", "Juice", "Oil"] },
                    { question: "Which animal is known as man's best friend?", correct: "Dog", wrong: ["Cat", "Horse", "Rabbit"] },
                    { question: "What part of the body helps us see?", correct: "Eyes", wrong: ["Ears", "Nose", "Mouth"] },
                    { question: "Which organ covers the human body?", correct: "Skin", wrong: ["Liver", "Lungs", "Heart"] },
                    { question: "What do plants need from sunlight to make food?", correct: "Energy", wrong: ["Water", "Soil", "Air"] },
                    { question: "Which bird is known for saying 'Polly wants a cracker'?", correct: "Parrot", wrong: ["Crow", "Eagle", "Owl"] },
                    { question: "Which animal lives both on land and in water?", correct: "Frog", wrong: ["Snake", "Dog", "Tiger"] },
                    { question: "What do you call baby cats?", correct: "Kittens", wrong: ["Puppies", "Cubs", "Chicks"] },
                    { question: "Which animal gives us wool?", correct: "Sheep", wrong: ["Cow", "Goat", "Horse"] },
                    { question: "What do you call a group of fish?", correct: "School", wrong: ["Pack", "Flock", "Herd"] },
                    { question: "What food do pandas mostly eat?", correct: "Bamboo", wrong: ["Grass", "Leaves", "Fruit"] },
                    { question: "Which animal has a trunk?", correct: "Elephant", wrong: ["Giraffe", "Hippopotamus", "Camel"] },
                ],
                physics: [
                    { question: "What force pulls objects toward Earth?", correct: "Gravity", wrong: ["Magnetism", "Friction", "Electricity"] },
                    { question: "What is the source of light on Earth?", correct: "The Sun", wrong: ["Moon", "Stars", "Fire"] },
                    { question: "Which device is used to see far objects?", correct: "Telescope", wrong: ["Microscope", "Binoculars", "Camera"] },
                    { question: "What energy makes things hot?", correct: "Heat", wrong: ["Light", "Sound", "Magnetism"] },
                    { question: "What do we call stored energy?", correct: "Potential energy", wrong: ["Kinetic energy", "Heat energy", "Light energy"] },
                    { question: "Which force slows down moving objects?", correct: "Friction", wrong: ["Gravity", "Magnetism", "Electricity"] },
                    { question: "Which simple machine is used to lift heavy objects?", correct: "Lever", wrong: ["Pulley", "Screw", "Wheel"] },
                    { question: "Which material is attracted by magnets?", correct: "Iron", wrong: ["Wood", "Plastic", "Paper"] },
                    { question: "What travels faster than sound?", correct: "Light", wrong: ["Water", "Wind", "Car"] },
                    { question: "Which type of energy is in moving objects?", correct: "Kinetic energy", wrong: ["Potential energy", "Heat energy", "Chemical energy"] },
                    { question: "What do we use to measure time?", correct: "Clock", wrong: ["Scale", "Meter", "Compass"] },
                    { question: "What is the opposite of push?", correct: "Pull", wrong: ["Lift", "Drop", "Throw"] },
                    { question: "Which instrument measures temperature?", correct: "Thermometer", wrong: ["Barometer", "Speedometer", "Altimeter"] },
                    { question: "What force keeps us from floating away?", correct: "Gravity", wrong: ["Magnetism", "Friction", "Pressure"] },
                    { question: "Which form of energy is used in light bulbs?", correct: "Electricity", wrong: ["Heat", "Magnetism", "Sound"] },
                    { question: "Which planet is closest to the Sun?", correct: "Mercury", wrong: ["Venus", "Earth", "Mars"] },
                    { question: "Which energy is stored in food?", correct: "Chemical energy", wrong: ["Heat energy", "Nuclear energy", "Kinetic energy"] },
                    { question: "What travels in straight lines and lets us see?", correct: "Light", wrong: ["Sound", "Heat", "Magnetism"] },
                    { question: "What type of energy is sound?", correct: "Vibrational energy", wrong: ["Light energy", "Heat energy", "Kinetic energy"] },
                    { question: "Which unit measures force?", correct: "Newton", wrong: ["Joule", "Watt", "Volt"] },
                ],
                chemistry: [
                    { question: "What is H₂O?", correct: "Water", wrong: ["Oxygen", "Hydrogen", "Carbon dioxide"] },
                    { question: "What do we call the simplest type of substance?", correct: "Element", wrong: ["Compound", "Mixture", "Solution"] },
                    { question: "What gas do plants release?", correct: "Oxygen", wrong: ["Carbon dioxide", "Nitrogen", "Hydrogen"] },
                    { question: "What taste does an acid usually have?", correct: "Sour", wrong: ["Bitter", "Sweet", "Salty"] },
                    { question: "Which gas do humans breathe out?", correct: "Carbon dioxide", wrong: ["Oxygen", "Hydrogen", "Nitrogen"] },
                    { question: "What do we call a mixture of metals?", correct: "Alloy", wrong: ["Solution", "Compound", "Element"] },
                    { question: "Which substance makes up diamonds?", correct: "Carbon", wrong: ["Oxygen", "Silicon", "Hydrogen"] },
                    { question: "What do we call table salt?", correct: "Sodium chloride", wrong: ["Calcium chloride", "Potassium nitrate", "Magnesium oxide"] },
                    { question: "Which element has the symbol O?", correct: "Oxygen", wrong: ["Gold", "Osmium", "Oxide"] },
                    { question: "What is the chemical symbol for gold?", correct: "Au", wrong: ["Ag", "G", "Go"] },
                    { question: "What do we call the air we breathe?", correct: "Atmosphere", wrong: ["Oxygen", "Carbon dioxide", "Nitrogen"] },
                    { question: "What is NaCl?", correct: "Salt", wrong: ["Sugar", "Water", "Ammonia"] },
                    { question: "Which element's symbol is H?", correct: "Hydrogen", wrong: ["Helium", "Hafnium", "Holmium"] },
                    { question: "What is the chemical symbol for silver?", correct: "Ag", wrong: ["Si", "S", "Au"] },
                    { question: "What substance is used in pencils?", correct: "Graphite", wrong: ["Lead", "Charcoal", "Carbon dioxide"] },
                    { question: "What gas makes balloons float?", correct: "Helium", wrong: ["Oxygen", "Nitrogen", "Carbon dioxide"] },
                    { question: "Which acid is found in lemons?", correct: "Citric acid", wrong: ["Acetic acid", "Sulfuric acid", "Lactic acid"] },
                    { question: "What is the pH of pure water?", correct: "7", wrong: ["5", "1", "10"] },
                    { question: "Which element is most abundant in the universe?", correct: "Hydrogen", wrong: ["Oxygen", "Carbon", "Nitrogen"] },
                    { question: "What is CO₂ commonly called?", correct: "Carbon dioxide", wrong: ["Carbon monoxide", "Oxygen", "Nitrogen"] },
                ],
                earth: [
                    { question: "What planet do we live on?", correct: "Earth", wrong: ["Mars", "Venus", "Jupiter"] },
                    { question: "What natural satellite orbits Earth?", correct: "The Moon", wrong: ["The Sun", "Asteroid", "Star"] },
                    { question: "What covers most of Earth's surface?", correct: "Water", wrong: ["Land", "Mountains", "Ice"] },
                    { question: "What do we call frozen water?", correct: "Ice", wrong: ["Steam", "Salt", "Gas"] },
                    { question: "Which planet is known as the Red Planet?", correct: "Mars", wrong: ["Venus", "Jupiter", "Mercury"] },
                    { question: "What is the hottest planet in our solar system?", correct: "Venus", wrong: ["Mercury", "Mars", "Jupiter"] },
                    { question: "What do we call a scientist who studies rocks?", correct: "Geologist", wrong: ["Astronomer", "Biologist", "Chemist"] },
                    { question: "Which layer of Earth do we live on?", correct: "Crust", wrong: ["Mantle", "Core", "Outer core"] },
                    { question: "What is the largest ocean on Earth?", correct: "Pacific Ocean", wrong: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"] },
                    { question: "Which gas makes up most of the Earth's atmosphere?", correct: "Nitrogen", wrong: ["Oxygen", "Carbon dioxide", "Hydrogen"] },
                    { question: "Which continent is the largest?", correct: "Asia", wrong: ["Africa", "North America", "Europe"] },
                    { question: "Which continent is the smallest?", correct: "Australia", wrong: ["Europe", "South America", "Antarctica"] },
                    { question: "What is the highest mountain in the world?", correct: "Mount Everest", wrong: ["K2", "Kilimanjaro", "Makalu"] },
                    { question: "Which ocean is the smallest?", correct: "Arctic Ocean", wrong: ["Indian Ocean", "Atlantic Ocean", "Pacific Ocean"] },
                    { question: "Which desert is the largest in the world?", correct: "Sahara Desert", wrong: ["Gobi Desert", "Kalahari Desert", "Great Victoria Desert"] },
                    { question: "What do we call molten rock under Earth's surface?", correct: "Magma", wrong: ["Lava", "Basalt", "Granite"] },
                    { question: "What do we call molten rock when it comes out of a volcano?", correct: "Lava", wrong: ["Magma", "Ash", "Smoke"] },
                    { question: "What is Earth's only natural satellite?", correct: "The Moon", wrong: ["Mars", "Phobos", "Sun"] },
                    { question: "What season comes after summer?", correct: "Autumn", wrong: ["Spring", "Winter", "Rainy"] },
                    { question: "Which planet is called the 'Blue Planet'?", correct: "Earth", wrong: ["Neptune", "Mars", "Venus"] },
                ],
            },
            medium: {
                biology: [
                    { question: "What part of the cell contains genetic material?", correct: "Nucleus", wrong: ["Cytoplasm", "Membrane", "Ribosome"] },
                    { question: "Which blood cells fight infection?", correct: "White blood cells", wrong: ["Red blood cells", "Platelets", "Plasma"] },
                    { question: "What gas do humans exhale?", correct: "Carbon dioxide", wrong: ["Oxygen", "Nitrogen", "Hydrogen"] },
                    { question: "Which organ pumps blood?", correct: "Heart", wrong: ["Lungs", "Brain", "Liver"] },
                    { question: "Which organ filters blood in the human body?", correct: "Kidney", wrong: ["Liver", "Lungs", "Pancreas"] },
                    { question: "What pigment makes plants green?", correct: "Chlorophyll", wrong: ["Melanin", "Carotene", "Xanthophyll"] },
                    { question: "Which organ helps us breathe?", correct: "Lungs", wrong: ["Stomach", "Kidneys", "Heart"] },
                    { question: "What type of blood carries oxygen?", correct: "Red blood cells", wrong: ["White blood cells", "Plasma", "Platelets"] },
                    { question: "What structure connects muscles to bones?", correct: "Tendon", wrong: ["Ligament", "Cartilage", "Nerves"] },
                    { question: "What system controls voluntary movement?", correct: "Nervous system", wrong: ["Respiratory system", "Digestive system", "Endocrine system"] },
                    { question: "Which organ produces insulin?", correct: "Pancreas", wrong: ["Liver", "Kidney", "Stomach"] },
                    { question: "What is the largest organ in the human body?", correct: "Skin", wrong: ["Heart", "Liver", "Lungs"] },
                    { question: "What gas do plants take in during photosynthesis?", correct: "Carbon dioxide", wrong: ["Oxygen", "Nitrogen", "Hydrogen"] },
                    { question: "What is the process of breaking down food called?", correct: "Digestion", wrong: ["Respiration", "Absorption", "Circulation"] },
                    { question: "What organ is responsible for detoxifying chemicals?", correct: "Liver", wrong: ["Kidney", "Stomach", "Lungs"] },
                    { question: "Which blood type is the universal donor?", correct: "O-", wrong: ["A", "B", "AB+"] },
                    { question: "What is the hardest substance in the human body?", correct: "Tooth enamel", wrong: ["Bone", "Cartilage", "Nail"] },
                    { question: "What organelle is known as the powerhouse of the cell?", correct: "Mitochondria", wrong: ["Nucleus", "Ribosome", "Golgi apparatus"] },
                    { question: "What carries messages between the brain and body?", correct: "Nerves", wrong: ["Arteries", "Veins", "Muscles"] },
                    { question: "Which part of the brain controls balance?", correct: "Cerebellum", wrong: ["Cerebrum", "Brainstem", "Hypothalamus"] },
                ],
                physics: [
                    { question: "What is the speed of light?", correct: "300,000 km/s", wrong: ["30,000 km/s", "300 km/s", "3,000 km/s"] },
                    { question: "What energy is stored in food?", correct: "Chemical energy", wrong: ["Heat energy", "Nuclear energy", "Light energy"] },
                    { question: "What is measured in Newtons?", correct: "Force", wrong: ["Energy", "Mass", "Temperature"] },
                    { question: "What type of energy does a moving car have?", correct: "Kinetic", wrong: ["Potential", "Thermal", "Nuclear"] },
                    { question: "What simple machine is a seesaw?", correct: "Lever", wrong: ["Pulley", "Inclined plane", "Screw"] },
                    { question: "What unit is used to measure power?", correct: "Watt", wrong: ["Joule", "Newton", "Ampere"] },
                    { question: "What is the force that slows objects moving through air?", correct: "Air resistance", wrong: ["Gravity", "Magnetism", "Tension"] },
                    { question: "What type of energy does a stretched rubber band have?", correct: "Elastic potential", wrong: ["Kinetic", "Thermal", "Nuclear"] },
                    { question: "Which law states that for every action there is an equal and opposite reaction?", correct: "Newton's Third Law", wrong: ["First Law", "Second Law", "Law of Gravity"] },
                    { question: "What instrument measures electric current?", correct: "Ammeter", wrong: ["Voltmeter", "Barometer", "Thermometer"] },
                    { question: "What does a prism do to light?", correct: "Splits it into colors", wrong: ["Magnifies it", "Absorbs it", "Reflects it"] },
                    { question: "Which type of wave needs no medium to travel?", correct: "Electromagnetic", wrong: ["Sound", "Water", "Seismic"] },
                    { question: "What is the acceleration due to gravity on Earth?", correct: "9.8 m/s²", wrong: ["10 m/s²", "8 m/s²", "12 m/s²"] },
                    { question: "What is the unit of frequency?", correct: "Hertz", wrong: ["Joule", "Newton", "Ohm"] },
                    { question: "What does a convex lens do?", correct: "Converges light rays", wrong: ["Diverges rays", "Blocks rays", "Scatters rays"] },
                    { question: "What kind of energy is sunlight?", correct: "Radiant energy", wrong: ["Chemical energy", "Thermal energy", "Nuclear energy"] },
                    { question: "What part of an atom has a positive charge?", correct: "Proton", wrong: ["Electron", "Neutron", "Nucleus"] },
                    { question: "What is sound caused by?", correct: "Vibrations", wrong: ["Reflections", "Refractions", "Waves only"] },
                    { question: "What type of current flows in one direction only?", correct: "Direct current (DC)", wrong: ["Alternating current (AC)", "Static current", "Dynamic current"] },
                    { question: "What type of energy is released in nuclear reactions?", correct: "Nuclear energy", wrong: ["Thermal", "Kinetic", "Radiant"] },
                ],
                chemistry: [
                    { question: "What is NaCl?", correct: "Salt", wrong: ["Sugar", "Water", "Vinegar"] },
                    { question: "What particle has a negative charge?", correct: "Electron", wrong: ["Proton", "Neutron", "Atom"] },
                    { question: "What is the chemical symbol for gold?", correct: "Au", wrong: ["Ag", "Fe", "Gd"] },
                    { question: "Which gas is used in balloons?", correct: "Helium", wrong: ["Hydrogen", "Oxygen", "Nitrogen"] },
                    { question: "What is the chemical symbol for sodium?", correct: "Na", wrong: ["So", "S", "Sn"] },
                    { question: "What element does 'O' represent?", correct: "Oxygen", wrong: ["Osmium", "Gold", "Hydrogen"] },
                    { question: "Which element has the chemical symbol 'Fe'?", correct: "Iron", wrong: ["Fluorine", "Lead", "Zinc"] },
                    { question: "What gas is needed for combustion?", correct: "Oxygen", wrong: ["Carbon dioxide", "Hydrogen", "Nitrogen"] },
                    { question: "What do we call a mixture of metals?", correct: "Alloy", wrong: ["Compound", "Solution", "Molecule"] },
                    { question: "What is the pH of pure water?", correct: "7", wrong: ["0", "14", "5"] },
                    { question: "What acid is found in lemons?", correct: "Citric acid", wrong: ["Sulfuric acid", "Acetic acid", "Lactic acid"] },
                    { question: "Which element is a liquid at room temperature?", correct: "Mercury", wrong: ["Iron", "Sodium", "Lead"] },
                    { question: "Which gas makes up most of Earth's atmosphere?", correct: "Nitrogen", wrong: ["Oxygen", "Carbon dioxide", "Argon"] },
                    { question: "What is the chemical symbol for silver?", correct: "Ag", wrong: ["Au", "Si", "S"] },
                    { question: "Which element is the lightest?", correct: "Hydrogen", wrong: ["Helium", "Lithium", "Carbon"] },
                    { question: "Which process separates salt from water?", correct: "Distillation", wrong: ["Filtration", "Evaporation", "Condensation"] },
                    { question: "What is the common name for H2O2?", correct: "Hydrogen peroxide", wrong: ["Water", "Ozone", "Acid"] },
                    { question: "What is the chemical formula for methane?", correct: "CH4", wrong: ["CO2", "C2H6", "C6H12O6"] },
                    { question: "Which gas turns limewater milky?", correct: "Carbon dioxide", wrong: ["Oxygen", "Nitrogen", "Hydrogen"] },
                    { question: "Which acid is present in vinegar?", correct: "Acetic acid", wrong: ["Sulfuric acid", "Nitric acid", "Citric acid"] },
                ],
                earth: [
                    { question: "What is the largest ocean?", correct: "Pacific Ocean", wrong: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"] },
                    { question: "Which layer of Earth do we live on?", correct: "Crust", wrong: ["Mantle", "Core", "Lithosphere"] },
                    { question: "What type of rock is formed from lava?", correct: "Igneous", wrong: ["Sedimentary", "Metamorphic", "Fossil"] },
                    { question: "What causes day and night?", correct: "Earth's rotation", wrong: ["Earth's revolution", "Moon's orbit", "Sun's rotation"] },
                    { question: "Which is the largest continent?", correct: "Asia", wrong: ["Africa", "North America", "Europe"] },
                    { question: "What do we call molten rock under Earth's surface?", correct: "Magma", wrong: ["Lava", "Basalt", "Granite"] },
                    { question: "Which planet is known as the Red Planet?", correct: "Mars", wrong: ["Venus", "Jupiter", "Mercury"] },
                    { question: "Which gas causes the greenhouse effect?", correct: "Carbon dioxide", wrong: ["Oxygen", "Nitrogen", "Helium"] },
                    { question: "What is Earth's only natural satellite?", correct: "The Moon", wrong: ["Phobos", "Sun", "Europa"] },
                    { question: "What natural disaster is measured by the Richter scale?", correct: "Earthquake", wrong: ["Volcano", "Flood", "Tornado"] },
                    { question: "What is the hottest planet in the solar system?", correct: "Venus", wrong: ["Mercury", "Mars", "Jupiter"] },
                    { question: "Which layer of Earth is liquid?", correct: "Outer core", wrong: ["Inner core", "Mantle", "Crust"] },
                    { question: "What is the study of weather called?", correct: "Meteorology", wrong: ["Geology", "Astronomy", "Climatology"] },
                    { question: "What is the largest desert in the world?", correct: "Sahara", wrong: ["Gobi", "Kalahari", "Arctic"] },
                    { question: "Which planet has the most moons?", correct: "Saturn", wrong: ["Jupiter", "Mars", "Neptune"] },
                    { question: "What is the main gas in Earth's atmosphere?", correct: "Nitrogen", wrong: ["Oxygen", "Carbon dioxide", "Argon"] },
                    { question: "Which ocean is the smallest?", correct: "Arctic Ocean", wrong: ["Indian Ocean", "Pacific Ocean", "Atlantic Ocean"] },
                    { question: "What is the Earth's longest river?", correct: "Nile", wrong: ["Amazon", "Yangtze", "Mississippi"] },
                    { question: "What is the coldest continent?", correct: "Antarctica", wrong: ["Europe", "Asia", "North America"] },
                    { question: "Which country has the most volcanoes?", correct: "Indonesia", wrong: ["Japan", "USA", "Iceland"] },
                ],
            },
            hard: {
                biology: [
                    { question: "What sugar is found in DNA?", correct: "Deoxyribose", wrong: ["Ribose", "Glucose", "Sucrose"] },
                    { question: "What organelle is the powerhouse of the cell?", correct: "Mitochondria", wrong: ["Nucleus", "Ribosome", "Golgi body"] },
                    { question: "What process makes gametes?", correct: "Meiosis", wrong: ["Mitosis", "Fertilization", "Replication"] },
                    { question: "What pigment captures light in photosynthesis?", correct: "Chlorophyll", wrong: ["Hemoglobin", "Carotene", "Melanin"] },
                    { question: "Which blood type is the universal donor?", correct: "O-", wrong: ["O+", "AB+", "A+"] },
                    { question: "Which vitamin helps in blood clotting?", correct: "Vitamin K", wrong: ["Vitamin A", "Vitamin C", "Vitamin D"] },
                    { question: "What is the largest organ in the human body?", correct: "Skin", wrong: ["Liver", "Lungs", "Heart"] },
                    { question: "What is the scientific name for red blood cells?", correct: "Erythrocytes", wrong: ["Leukocytes", "Platelets", "Plasma"] },
                    { question: "What is the fluid inside a cell called?", correct: "Cytoplasm", wrong: ["Nucleoplasm", "Chloroplast", "Mitochondria"] },
                    { question: "Which part of the brain controls balance?", correct: "Cerebellum", wrong: ["Cerebrum", "Medulla", "Hypothalamus"] },
                    { question: "What do ribosomes produce?", correct: "Proteins", wrong: ["Lipids", "Carbohydrates", "DNA"] },
                    { question: "Which enzyme breaks down starch?", correct: "Amylase", wrong: ["Lipase", "Protease", "Lactase"] },
                    { question: "What is the term for maintaining stable internal conditions?", correct: "Homeostasis", wrong: ["Metabolism", "Equilibrium", "Regulation"] },
                    { question: "What type of reproduction involves one parent?", correct: "Asexual", wrong: ["Sexual", "Binary fusion", "Meiosis"] },
                    { question: "Which human organ produces insulin?", correct: "Pancreas", wrong: ["Liver", "Kidney", "Stomach"] },
                    { question: "Which blood vessels carry blood away from the heart?", correct: "Arteries", wrong: ["Veins", "Capillaries", "Valves"] },
                    { question: "Which part of the plant carries water upward?", correct: "Xylem", wrong: ["Phloem", "Stomata", "Chloroplast"] },
                    { question: "What is the basic functional unit of the kidney?", correct: "Nephron", wrong: ["Alveoli", "Neuron", "Glomerulus"] },
                    { question: "Which nucleic acid is single-stranded?", correct: "RNA", wrong: ["DNA", "Protein", "ATP"] },
                    { question: "What organ filters blood in the human body?", correct: "Kidney", wrong: ["Liver", "Heart", "Lungs"] },
                ],
                physics: [
                    { question: "Who proposed the theory of relativity?", correct: "Einstein", wrong: ["Newton", "Galileo", "Tesla"] },
                    { question: "What is absolute zero in Celsius?", correct: "-273°C", wrong: ["0°C", "-100°C", "-459°C"] },
                    { question: "What subatomic particle has no charge?", correct: "Neutron", wrong: ["Proton", "Electron", "Positron"] },
                    { question: "What law explains action and reaction?", correct: "Newton's Third Law", wrong: ["First Law", "Second Law", "Law of Gravity"] },
                    { question: "What is the unit of electrical resistance?", correct: "Ohm", wrong: ["Watt", "Ampere", "Volt"] },
                    { question: "What is the escape velocity from Earth?", correct: "11.2 km/s", wrong: ["7.9 km/s", "9.8 km/s", "15 km/s"] },
                    { question: "What is the weakest force in nature?", correct: "Gravitational", wrong: ["Electromagnetic", "Nuclear", "Magnetic"] },
                    { question: "What phenomenon causes red shift?", correct: "Doppler Effect", wrong: ["Reflection", "Diffraction", "Refraction"] },
                    { question: "What is the SI unit of power?", correct: "Watt", wrong: ["Joule", "Newton", "Volt"] },
                    { question: "Which scientist discovered radioactivity?", correct: "Henri Becquerel", wrong: ["Marie Curie", "Rutherford", "Einstein"] },
                    { question: "What type of lens is used in a magnifying glass?", correct: "Convex", wrong: ["Concave", "Plane", "Cylindrical"] },
                    { question: "What is the bending of light called?", correct: "Refraction", wrong: ["Reflection", "Diffraction", "Dispersion"] },
                    { question: "Which law relates pressure and volume of gas?", correct: "Boyle's Law", wrong: ["Charles's Law", "Avogadro's Law", "Dalton's Law"] },
                    { question: "What is the most penetrating radiation?", correct: "Gamma rays", wrong: ["Alpha rays", "Beta rays", "X-rays"] },
                    { question: "Which particles carry electric current in metals?", correct: "Electrons", wrong: ["Protons", "Neutrons", "Ions"] },
                    { question: "What type of wave is sound?", correct: "Longitudinal", wrong: ["Transverse", "Electromagnetic", "Stationary"] },
                    { question: "What is measured in Hertz?", correct: "Frequency", wrong: ["Wavelength", "Amplitude", "Speed"] },
                    { question: "What is the branch of physics dealing with heat?", correct: "Thermodynamics", wrong: ["Kinetics", "Electrodynamics", "Mechanics"] },
                    { question: "What is the angle of incidence equal to?", correct: "Angle of reflection", wrong: ["Refraction angle", "90°", "Critical angle"] },
                    { question: "What type of energy is in a stretched spring?", correct: "Potential", wrong: ["Kinetic", "Thermal", "Nuclear"] },
                ],
                chemistry: [
                    { question: "What is the pH of pure water?", correct: "7", wrong: ["0", "14", "5"] },
                    { question: "Which element has atomic number 6?", correct: "Carbon", wrong: ["Oxygen", "Nitrogen", "Helium"] },
                    { question: "What bond shares electrons?", correct: "Covalent", wrong: ["Ionic", "Hydrogen", "Metallic"] },
                    { question: "Which acid is found in the stomach?", correct: "Hydrochloric acid", wrong: ["Sulfuric acid", "Nitric acid", "Carbonic acid"] },
                    { question: "What is the lightest element?", correct: "Hydrogen", wrong: ["Helium", "Lithium", "Neon"] },
                    { question: "What is CH₄?", correct: "Methane", wrong: ["Ethane", "Propane", "Butane"] },
                    { question: "Who created the periodic table?", correct: "Mendeleev", wrong: ["Dalton", "Bohr", "Curie"] },
                    { question: "Which gas turns limewater milky?", correct: "Carbon dioxide", wrong: ["Oxygen", "Nitrogen", "Hydrogen"] },
                    { question: "What type of reaction releases heat?", correct: "Exothermic", wrong: ["Endothermic", "Neutralization", "Combustion"] },
                    { question: "What is the chemical symbol for Mercury?", correct: "Hg", wrong: ["Me", "Mr", "Mc"] },
                    { question: "Which element is used in thermometers?", correct: "Mercury", wrong: ["Lead", "Zinc", "Copper"] },
                    { question: "What is the Avogadro's number?", correct: "6.022×10²³", wrong: ["3.14", "9.81", "1.6×10⁻¹⁹"] },
                    { question: "What is the main gas in Earth's atmosphere?", correct: "Nitrogen", wrong: ["Oxygen", "Carbon dioxide", "Hydrogen"] },
                    { question: "Which metal is liquid at room temperature?", correct: "Mercury", wrong: ["Sodium", "Potassium", "Aluminum"] },
                    { question: "Which acid is found in vinegar?", correct: "Acetic acid", wrong: ["Citric acid", "Sulfuric acid", "Formic acid"] },
                    { question: "Which gas is called laughing gas?", correct: "Nitrous oxide", wrong: ["Carbon monoxide", "Oxygen", "Hydrogen"] },
                    { question: "What type of ions do acids produce?", correct: "H+ ions", wrong: ["OH- ions", "Na+ ions", "Cl- ions"] },
                    { question: "What is the chemical symbol for silver?", correct: "Ag", wrong: ["Au", "Si", "Pb"] },
                    { question: "What is the hardest natural substance?", correct: "Diamond", wrong: ["Quartz", "Graphite", "Corundum"] },
                    { question: "Which element has the symbol 'K'?", correct: "Potassium", wrong: ["Calcium", "Krypton", "Phosphorus"] },
                ],
                earth: [
                    { question: "What type of rock forms from pressure and heat?", correct: "Metamorphic", wrong: ["Igneous", "Sedimentary", "Volcanic"] },
                    { question: "Which layer of Earth is liquid?", correct: "Outer core", wrong: ["Inner core", "Mantle", "Crust"] },
                    { question: "What is the largest planet in our solar system?", correct: "Jupiter", wrong: ["Saturn", "Earth", "Neptune"] },
                    { question: "What causes tides on Earth?", correct: "Moon's gravity", wrong: ["Sun's heat", "Earth's spin", "Wind"] },
                    { question: "What is the hottest planet in the solar system?", correct: "Venus", wrong: ["Mercury", "Mars", "Jupiter"] },
                    { question: "What is the Earth's most abundant gas?", correct: "Nitrogen", wrong: ["Oxygen", "Carbon dioxide", "Argon"] },
                    { question: "What galaxy do we live in?", correct: "Milky Way", wrong: ["Andromeda", "Whirlpool", "Sombrero"] },
                    { question: "What is the largest desert on Earth?", correct: "Antarctic Desert", wrong: ["Sahara", "Arctic", "Gobi"] },
                    { question: "What is the deepest ocean trench?", correct: "Mariana Trench", wrong: ["Puerto Rico Trench", "Java Trench", "Tonga Trench"] },
                    { question: "What is the study of earthquakes called?", correct: "Seismology", wrong: ["Volcanology", "Geology", "Astronomy"] },
                    { question: "What is the smallest planet in our solar system?", correct: "Mercury", wrong: ["Mars", "Venus", "Pluto"] },
                    { question: "What is Earth's primary source of energy?", correct: "The Sun", wrong: ["The Moon", "Volcanoes", "Earth's core"] },
                    { question: "What type of galaxy is the Milky Way?", correct: "Spiral", wrong: ["Elliptical", "Irregular", "Lenticular"] },
                    { question: "What is the Earth's innermost layer?", correct: "Inner core", wrong: ["Outer core", "Mantle", "Crust"] },
                    { question: "What is the tallest mountain on Earth?", correct: "Mount Everest", wrong: ["K2", "Kangchenjunga", "Makalu"] },
                    { question: "Which planet is known as the Red Planet?", correct: "Mars", wrong: ["Jupiter", "Venus", "Saturn"] },
                    { question: "What causes the aurora borealis?", correct: "Solar wind", wrong: ["Moonlight", "Earth’s rotation", "Volcanoes"] },
                    { question: "What is Earth’s only natural satellite?", correct: "The Moon", wrong: ["Phobos", "Titan", "Europa"] },
                    { question: "Which planet has the most moons?", correct: "Saturn", wrong: ["Jupiter", "Uranus", "Neptune"] },
                    { question: "What is the most common rock on Earth’s crust?", correct: "Basalt", wrong: ["Granite", "Limestone", "Sandstone"] },
                ],
            }
        };

export default scienceSets;
