const wordSets = {
            easy: {
                synonym: [
                    { word: "happy", correct: "joyful", wrong: ["sad", "angry", "tired"] },
                    { word: "big", correct: "large", wrong: ["small", "tiny", "little"] },
                    { word: "fast", correct: "quick", wrong: ["slow", "lazy", "tired"] },
                    { word: "smart", correct: "clever", wrong: ["dumb", "silly", "lazy"] },
                    { word: "angry", correct: "furious", wrong: ["happy", "calm", "joyful"] },
                    { word: "easy", correct: "simple", wrong: ["difficult", "hard", "complex"] },
                    { word: "strong", correct: "powerful", wrong: ["weak", "fragile", "small"] },
                    { word: "brave", correct: "courageous", wrong: ["scared", "timid", "weak"] },
                    { word: "quiet", correct: "silent", wrong: ["loud", "noisy", "talkative"] },
                    { word: "beautiful", correct: "gorgeous", wrong: ["ugly", "plain", "boring"] },
                    { word: "sad", correct: "unhappy", wrong: ["joyful", "funny", "excited"] },
                    { word: "cold", correct: "chilly", wrong: ["hot", "warm", "boiling"] },
                    { word: "clean", correct: "tidy", wrong: ["dirty", "messy", "ugly"] },
                    { word: "funny", correct: "hilarious", wrong: ["serious", "boring", "sad"] },
                    { word: "hard", correct: "difficult", wrong: ["easy", "simple", "soft"] },
                    { word: "rich", correct: "wealthy", wrong: ["poor", "broke", "hungry"] },
                    { word: "good", correct: "nice", wrong: ["bad", "evil", "awful"] },
                    { word: "bad", correct: "awful", wrong: ["great", "kind", "funny"] },
                    { word: "quick", correct: "rapid", wrong: ["slow", "lazy", "weak"] },
                    { word: "child", correct: "kid", wrong: ["adult", "man", "old"] },
                ],
                antonym: [
                    { word: "hot", correct: "cold", wrong: ["warm", "cool", "mild"] },
                    { word: "up", correct: "down", wrong: ["over", "under", "above"] },
                    { word: "good", correct: "bad", wrong: ["nice", "great", "fine"] },
                    { word: "light", correct: "dark", wrong: ["bright", "clear", "white"] },
                    { word: "happy", correct: "sad", wrong: ["joyful", "excited", "glad"] },
                    { word: "big", correct: "small", wrong: ["large", "huge", "gigantic"] },
                    { word: "fast", correct: "slow", wrong: ["quick", "rapid", "swift"] },
                    { word: "strong", correct: "weak", wrong: ["powerful", "mighty", "sturdy"] },
                    { word: "young", correct: "old", wrong: ["new", "fresh", "recent"] },
                    { word: "near", correct: "far", wrong: ["close", "next", "adjacent"] },
                    { word: "begin", correct: "end", wrong: ["start", "open", "play"] },
                    { word: "tall", correct: "short", wrong: ["long", "big", "high"] },
                    { word: "day", correct: "night", wrong: ["light", "sun", "time"] },
                    { word: "boy", correct: "girl", wrong: ["man", "uncle", "king"] },
                    { word: "asleep", correct: "awake", wrong: ["sleepy", "quiet", "lazy"] },
                    { word: "clean", correct: "dirty", wrong: ["tidy", "pure", "clear"] },
                    { word: "full", correct: "empty", wrong: ["big", "whole", "complete"] },
                    { word: "love", correct: "hate", wrong: ["like", "joy", "peace"] },
                    { word: "in", correct: "out", wrong: ["up", "over", "near"] },
                    { word: "give", correct: "take", wrong: ["bring", "help", "show"] },
                ],
                definition: [
                    { word: "cat", correct: "a small furry pet", wrong: ["a big dog", "a bird", "a fish"] },
                    { word: "book", correct: "something to read", wrong: ["something to eat", "something to wear", "something to drive"] },
                    { word: "apple", correct: "a type of fruit", wrong: ["a vegetable", "a tool", "a drink"] },
                    { word: "chair", correct: "something to sit on", wrong: ["something to sleep on", "something to write with", "something to wear"] },
                    { word: "river", correct: "a flowing body of water", wrong: ["a mountain", "a tree", "a road"] },
                    { word: "car", correct: "a vehicle for transport", wrong: ["a building", "a computer", "a tool"] },
                    { word: "shoe", correct: "something worn on the foot", wrong: ["something worn on the hand", "a hat", "a glove"] },
                    { word: "pencil", correct: "something used to write", wrong: ["something used to eat", "something used to paint", "something used to clean"] },
                    { word: "dog", correct: "a domesticated animal", wrong: ["a wild animal", "a bird", "a fish"] },
                    { word: "tree", correct: "a plant with a trunk and branches", wrong: ["a flower", "a bush", "a rock"] },
                    { word: "ball", correct: "something to play with", wrong: ["a food", "a shoe", "a bed"] },
                    { word: "bed", correct: "something to sleep on", wrong: ["something to sit on", "a car", "a book"] },
                    { word: "hat", correct: "something worn on the head", wrong: ["shoe", "glove", "pants"] },
                    { word: "milk", correct: "a drink from cows", wrong: ["fruit", "bread", "soup"] },
                    { word: "sun", correct: "the star that gives us light", wrong: ["moon", "lamp", "cloud"] },
                    { word: "fish", correct: "an animal that lives in water", wrong: ["dog", "bird", "cat"] },
                    { word: "clock", correct: "something that shows time", wrong: ["toy", "food", "book"] },
                    { word: "school", correct: "a place to learn", wrong: ["a house", "a park", "a shop"] },
                    { word: "banana", correct: "a yellow fruit", wrong: ["apple", "grape", "carrot"] },
                    { word: "road", correct: "a path for cars", wrong: ["river", "tree", "field"] },
                ],
                spelling: [
                    { word: "friend", correct: "friend", wrong: ["freind", "frend", "freand"] },
                    { word: "school", correct: "school", wrong: ["scool", "schol", "skool"] },
                    { word: "apple", correct: "apple", wrong: ["aple", "appel", "appl"] },
                    { word: "house", correct: "house", wrong: ["hous", "houes", "hoose"] },
                    { word: "computer", correct: "computer", wrong: ["computor", "compter", "comuter"] },
                    { word: "beautiful", correct: "beautiful", wrong: ["beatiful", "beutiful", "beautifull"] },
                    { word: "library", correct: "library", wrong: ["libary", "librery", "liberry"] },
                    { word: "holiday", correct: "holiday", wrong: ["holidy", "holoday", "holidey"] },
                    { word: "together", correct: "together", wrong: ["togther", "toether", "togehter"] },
                    { word: "because", correct: "because", wrong: ["becuase", "becase", "becouse"] },
                    { word: "family", correct: "family", wrong: ["famely", "famly", "familey"] },
                    { word: "teacher", correct: "teacher", wrong: ["techer", "tetcher", "techar"] },
                    { word: "mother", correct: "mother", wrong: ["moter", "mothar", "mothor"] },
                    { word: "father", correct: "father", wrong: ["fater", "fathar", "fathor"] },
                    { word: "animal", correct: "animal", wrong: ["anemal", "animel", "animil"] },
                    { word: "garden", correct: "garden", wrong: ["gardan", "gardon", "garedn"] },
                    { word: "orange", correct: "orange", wrong: ["orenge", "orrange", "orenj"] },
                    { word: "music", correct: "music", wrong: ["musick", "musik", "muic"] },
                    { word: "baby", correct: "baby", wrong: ["beby", "babey", "babby"] },
                    { word: "happy", correct: "happy", wrong: ["hapy", "hapey", "happi"] },
                ]
            },
            medium: {
                synonym: [
                    { word: "beautiful", correct: "gorgeous", wrong: ["ugly", "plain", "simple"] },
                    { word: "difficult", correct: "challenging", wrong: ["easy", "simple", "basic"] },
                    { word: "ancient", correct: "old", wrong: ["new", "modern", "recent"] },
                    { word: "quick", correct: "swift", wrong: ["slow", "lazy", "sluggish"] },
                    { word: "brave", correct: "courageous", wrong: ["scared", "timid", "weak"] },
                    { word: "smart", correct: "intelligent", wrong: ["dumb", "foolish", "slow"] },
                    { word: "strong", correct: "powerful", wrong: ["weak", "fragile", "feeble"] },
                    { word: "angry", correct: "furious", wrong: ["happy", "calm", "joyful"] },
                    { word: "funny", correct: "humorous", wrong: ["serious", "boring", "sad"] },
                    { word: "bright", correct: "luminous", wrong: ["dark", "dull", "dim"] },
                    { word: "tiny", correct: "minute", wrong: ["huge", "large", "giant"] },
                    { word: "happy", correct: "joyful", wrong: ["sad", "angry", "miserable"] },
                    { word: "calm", correct: "peaceful", wrong: ["noisy", "angry", "chaotic"] },
                    { word: "cold", correct: "chilly", wrong: ["hot", "warm", "boiling"] },
                    { word: "lazy", correct: "idle", wrong: ["active", "energetic", "busy"] },
                    { word: "friendly", correct: "amiable", wrong: ["mean", "hostile", "rude"] },
                    { word: "safe", correct: "secure", wrong: ["dangerous", "risky", "unsafe"] },
                    { word: "big", correct: "enormous", wrong: ["tiny", "small", "little"] },
                    { word: "sad", correct: "unhappy", wrong: ["joyful", "cheerful", "excited"] },
                    { word: "hardworking", correct: "diligent", wrong: ["lazy", "careless", "sloppy"] },
                ],

                antonym: [
                    { word: "expand", correct: "contract", wrong: ["grow", "increase", "enlarge"] },
                    { word: "victory", correct: "defeat", wrong: ["win", "success", "triumph"] },
                    { word: "ancient", correct: "modern", wrong: ["old", "historic", "past"] },
                    { word: "strong", correct: "weak", wrong: ["powerful", "robust", "tough"] },
                    { word: "happy", correct: "sad", wrong: ["joyful", "excited", "glad"] },
                    { word: "open", correct: "closed", wrong: ["shut", "ajar", "wide"] },
                    { word: "high", correct: "low", wrong: ["tall", "elevated", "above"] },
                    { word: "fast", correct: "slow", wrong: ["quick", "rapid", "swift"] },
                    { word: "bright", correct: "dark", wrong: ["luminous", "shiny", "glowing"] },
                    { word: "near", correct: "far", wrong: ["close", "next", "adjacent"] },
                    { word: "accept", correct: "reject", wrong: ["receive", "approve", "allow"] },
                    { word: "love", correct: "hate", wrong: ["like", "admire", "enjoy"] },
                    { word: "arrival", correct: "departure", wrong: ["coming", "entry", "approach"] },
                    { word: "include", correct: "exclude", wrong: ["allow", "add", "contain"] },
                    { word: "success", correct: "failure", wrong: ["achievement", "win", "victory"] },
                    { word: "public", correct: "private", wrong: ["open", "shared", "community"] },
                    { word: "asleep", correct: "awake", wrong: ["dreaming", "resting", "sleepy"] },
                    { word: "create", correct: "destroy", wrong: ["build", "design", "invent"] },
                    { word: "borrow", correct: "lend", wrong: ["take", "get", "receive"] },
                    { word: "arrival", correct: "departure", wrong: ["visit", "meeting", "welcome"] },
                ],

                definition: [
                    { word: "telescope", correct: "device to see far objects", wrong: ["device to hear sounds", "device to cook food", "device to clean"] },
                    { word: "volcano", correct: "mountain that erupts lava", wrong: ["lake", "river", "valley"] },
                    { word: "oxygen", correct: "gas we breathe", wrong: ["water", "carbon", "nitrogen"] },
                    { word: "keyboard", correct: "device to type on a computer", wrong: ["monitor", "mouse", "printer"] },
                    { word: "microscope", correct: "device to see tiny objects", wrong: ["telescope", "camera", "binoculars"] },
                    { word: "pyramid", correct: "triangular structure", wrong: ["cube", "sphere", "circle"] },
                    { word: "glacier", correct: "large ice mass", wrong: ["river", "mountain", "lake"] },
                    { word: "satellite", correct: "object orbiting a planet", wrong: ["rocket", "star", "moon"] },
                    { word: "guitar", correct: "stringed musical instrument", wrong: ["drum", "piano", "flute"] },
                    { word: "volleyball", correct: "sport played with a ball over a net", wrong: ["soccer", "tennis", "basketball"] },
                    { word: "atlas", correct: "book of maps", wrong: ["dictionary", "encyclopedia", "journal"] },
                    { word: "thermometer", correct: "instrument to measure temperature", wrong: ["barometer", "compass", "ruler"] },
                    { word: "battery", correct: "device that stores energy", wrong: ["engine", "fuel", "light"] },
                    { word: "planet", correct: "large object orbiting a star", wrong: ["asteroid", "comet", "satellite"] },
                    { word: "oxygen", correct: "gas essential for breathing", wrong: ["carbon", "hydrogen", "helium"] },
                    { word: "calendar", correct: "system to organize days", wrong: ["clock", "alarm", "timer"] },
                    { word: "dictionary", correct: "book with word meanings", wrong: ["atlas", "notebook", "encyclopedia"] },
                    { word: "binoculars", correct: "device to see distant objects", wrong: ["glasses", "microscope", "lens"] },
                    { word: "triangle", correct: "shape with three sides", wrong: ["square", "circle", "hexagon"] },
                    { word: "galaxy", correct: "system of stars", wrong: ["planet", "universe", "asteroid belt"] },
                ],

                spelling: [
                    { word: "necessary", correct: "necessary", wrong: ["neccessary", "necesary", "neccesary"] },
                    { word: "beautiful", correct: "beautiful", wrong: ["beatiful", "beutiful", "beautifull"] },
                    { word: "accommodate", correct: "accommodate", wrong: ["acommodate", "accomodate", "acomodate"] },
                    { word: "definitely", correct: "definitely", wrong: ["definately", "definitly", "definetly"] },
                    { word: "separate", correct: "separate", wrong: ["seperate", "seperete", "separite"] },
                    { word: "questionnaire", correct: "questionnaire", wrong: ["questionaire", "questinnaire", "questioner"] },
                    { word: "occurrence", correct: "occurrence", wrong: ["occurence", "ocurrence", "occurance"] },
                    { word: "acquire", correct: "acquire", wrong: ["aquire", "acqire", "acqure"] },
                    { word: "maintenance", correct: "maintenance", wrong: ["maintainance", "maintanance", "maintnance"] },
                    { word: "privilege", correct: "privilege", wrong: ["privelege", "priviledge", "privlig"] },
                    { word: "entrepreneur", correct: "entrepreneur", wrong: ["entrepeneur", "entreprenur", "enterprenuer"] },
                    { word: "recommend", correct: "recommend", wrong: ["reccomend", "recomend", "reccamend"] },
                    { word: "embarrass", correct: "embarrass", wrong: ["embarass", "embaras", "embarris"] },
                    { word: "rhythm", correct: "rhythm", wrong: ["rythm", "rithym", "rythem"] },
                    { word: "vacuum", correct: "vacuum", wrong: ["vaccum", "vacum", "vacuem"] },
                    { word: "millennium", correct: "millennium", wrong: ["millenium", "milennium", "milenium"] },
                    { word: "occasionally", correct: "occasionally", wrong: ["ocasionally", "occassionaly", "ocasionaly"] },
                    { word: "conscience", correct: "conscience", wrong: ["conciens", "conshens", "consiense"] },
                    { word: "hierarchy", correct: "hierarchy", wrong: ["heirarchy", "hierarcy", "hirarchy"] },
                    { word: "supersede", correct: "supersede", wrong: ["supercede", "supersceed", "suparseed"] },
                ],
            },
            hard: {
                synonym: [
                    { word: "ubiquitous", correct: "everywhere", wrong: ["rare", "hidden", "absent"] },
                    { word: "meticulous", correct: "careful", wrong: ["careless", "sloppy", "rushed"] },
                    { word: "obstinate", correct: "stubborn", wrong: ["flexible", "gentle", "yielding"] },
                    { word: "lucid", correct: "clear", wrong: ["confusing", "vague", "obscure"] },
                    { word: "tenacious", correct: "persistent", wrong: ["weak", "lazy", "indifferent"] },
                    { word: "esoteric", correct: "obscure", wrong: ["common", "famous", "popular"] },
                    { word: "ambiguous", correct: "unclear", wrong: ["obvious", "clear", "definite"] },
                    { word: "candid", correct: "honest", wrong: ["dishonest", "sly", "deceptive"] },
                    { word: "prudent", correct: "wise", wrong: ["reckless", "careless", "foolish"] },
                    { word: "profound", correct: "deep", wrong: ["shallow", "superficial", "simple"] },
                    { word: "arduous", correct: "difficult", wrong: ["easy", "simple", "effortless"] },
                    { word: "eloquent", correct: "fluent", wrong: ["awkward", "clumsy", "mute"] },
                    { word: "frugal", correct: "thrifty", wrong: ["wasteful", "lavish", "extravagant"] },
                    { word: "gregarious", correct: "sociable", wrong: ["shy", "introverted", "solitary"] },
                    { word: "incessant", correct: "continuous", wrong: ["intermittent", "rare", "occasional"] },
                    { word: "malevolent", correct: "evil", wrong: ["kind", "benevolent", "generous"] },
                    { word: "mundane", correct: "ordinary", wrong: ["extraordinary", "unique", "special"] },
                    { word: "succinct", correct: "brief", wrong: ["wordy", "lengthy", "long"] },
                    { word: "altruistic", correct: "selfless", wrong: ["selfish", "greedy", "egoistic"] },
                    { word: "capricious", correct: "unpredictable", wrong: ["consistent", "stable", "reliable"] },
                ],
                antonym: [
                    { word: "benevolent", correct: "malevolent", wrong: ["kind", "generous", "helpful"] },
                    { word: "ephemeral", correct: "permanent", wrong: ["temporary", "brief", "short"] },
                    { word: "ascend", correct: "descend", wrong: ["rise", "climb", "soar"] },
                    { word: "opaque", correct: "transparent", wrong: ["cloudy", "dark", "murky"] },
                    { word: "scarce", correct: "abundant", wrong: ["rare", "limited", "insufficient"] },
                    { word: "chaotic", correct: "orderly", wrong: ["messy", "confused", "disorganized"] },
                    { word: "artificial", correct: "natural", wrong: ["synthetic", "man-made", "engineered"] },
                    { word: "hostile", correct: "friendly", wrong: ["aggressive", "unfriendly", "harsh"] },
                    { word: "fragile", correct: "strong", wrong: ["weak", "delicate", "brittle"] },
                    { word: "vague", correct: "specific", wrong: ["unclear", "ambiguous", "imprecise"] },
                    { word: "timid", correct: "bold", wrong: ["fearful", "nervous", "shy"] },
                    { word: "ancient", correct: "modern", wrong: ["old", "antique", "historic"] },
                    { word: "expand", correct: "contract", wrong: ["grow", "enlarge", "stretch"] },
                    { word: "humble", correct: "arrogant", wrong: ["modest", "simple", "shy"] },
                    { word: "optimistic", correct: "pessimistic", wrong: ["hopeful", "cheerful", "positive"] },
                    { word: "tranquil", correct: "chaotic", wrong: ["calm", "peaceful", "quiet"] },
                    { word: "vivid", correct: "dull", wrong: ["bright", "colorful", "lively"] },
                    { word: "prosperity", correct: "poverty", wrong: ["wealth", "fortune", "abundance"] },
                    { word: "lenient", correct: "strict", wrong: ["forgiving", "kind", "merciful"] },
                    { word: "affirm", correct: "deny", wrong: ["accept", "agree", "confirm"] },
                ],
                definition: [
                    { word: "serendipity", correct: "pleasant surprise", wrong: ["bad luck", "planned event", "boring moment"] },
                    { word: "epiphany", correct: "sudden realization", wrong: ["confusion", "question", "mistake"] },
                    { word: "labyrinth", correct: "complex maze", wrong: ["simple path", "straight road", "open field"] },
                    { word: "paradox", correct: "contradictory statement", wrong: ["simple truth", "story", "fact"] },
                    { word: "quintessential", correct: "perfect example", wrong: ["worst example", "average", "rare"] },
                    { word: "mellifluous", correct: "pleasant-sounding", wrong: ["harsh", "ugly", "rough"] },
                    { word: "oblivion", correct: "state of being forgotten", wrong: ["fame", "attention", "recognition"] },
                    { word: "zenith", correct: "highest point", wrong: ["lowest point", "middle", "base"] },
                    { word: "cacophony", correct: "harsh noise", wrong: ["pleasant sound", "music", "silence"] },
                    { word: "ephemeral", correct: "short-lived", wrong: ["long-lasting", "permanent", "eternal"] },
                    { word: "facetious", correct: "not serious", wrong: ["serious", "genuine", "honest"] },
                    { word: "anachronism", correct: "out of place in time", wrong: ["timely", "modern", "current"] },
                    { word: "aesthetic", correct: "related to beauty", wrong: ["ugly", "plain", "ordinary"] },
                    { word: "eloquence", correct: "fluent speaking", wrong: ["silence", "awkwardness", "clumsiness"] },
                    { word: "hubris", correct: "excessive pride", wrong: ["humility", "kindness", "modesty"] },
                    { word: "ineffable", correct: "too great to express", wrong: ["obvious", "simple", "easy"] },
                    { word: "juxtapose", correct: "place side by side", wrong: ["separate", "ignore", "remove"] },
                    { word: "nostalgia", correct: "longing for the past", wrong: ["future hope", "present joy", "disinterest"] },
                    { word: "reverie", correct: "daydream", wrong: ["nightmare", "focus", "work"] },
                    { word: "sagacious", correct: "wise", wrong: ["foolish", "reckless", "ignorant"] },
                ],
                spelling: [
                    { word: "accommodate", correct: "accommodate", wrong: ["accomodate", "acomodate", "acommodate"] },
                    { word: "definitely", correct: "definitely", wrong: ["definately", "definitly", "definetly"] },
                    { word: "conscientious", correct: "conscientious", wrong: ["consciencious", "consientious", "conscientous"] },
                    { word: "pronunciation", correct: "pronunciation", wrong: ["pronounciation", "pronuntiation", "pronounciaton"] },
                    { word: "rhythm", correct: "rhythm", wrong: ["rythm", "rithm", "rhythem"] },
                    { word: "miscellaneous", correct: "miscellaneous", wrong: ["miscelaneous", "miscellanous", "micesllaneous"] },
                    { word: "occasionally", correct: "occasionally", wrong: ["ocasionally", "occassionally", "ocassionally"] },
                    { word: "embarrass", correct: "embarrass", wrong: ["embarass", "embarras", "embarrs"] },
                    { word: "harass", correct: "harass", wrong: ["harrass", "haras", "harres"] },
                    { word: "connoisseur", correct: "connoisseur", wrong: ["conaisseur", "connosieur", "connoiser"] },
                    { word: "supersede", correct: "supersede", wrong: ["supercede", "supersaid", "supersaid"] },
                    { word: "millennium", correct: "millennium", wrong: ["milenium", "millenium", "millennum"] },
                    { word: "indict", correct: "indict", wrong: ["indite", "indigt", "indickt"] },
                    { word: "pharaoh", correct: "pharaoh", wrong: ["pharoah", "pharoh", "pharow"] },
                    { word: "weird", correct: "weird", wrong: ["wierd", "weard", "waird"] },
                    { word: "guarantee", correct: "guarantee", wrong: ["garantee", "guarentee", "garente"] },
                    { word: "liaison", correct: "liaison", wrong: ["liason", "laiasone", "layazon"] },
                    { word: "recommend", correct: "recommend", wrong: ["reccomend", "recomend", "reccommand"] },
                    { word: "necessary", correct: "necessary", wrong: ["neccesary", "necesary", "nessesary"] },
                    { word: "questionnaire", correct: "questionnaire", wrong: ["questionare", "questonaire", "questionnare"] },
                ],
            }
        };


export default wordSets;